// 48 teams · groups per the official draw layout used in the design reference.
// rank / titles / appearances / squads are editable sample data.
export const T = [

  ["mex","Mexico","🇲🇽","A",14,0,18,"Co-hosts with home-crowd thunder — quick wingers and a fortress in the Azteca."],
  ["rsa","South Africa","🇿🇦","A",59,0,4,"Bafana Bafana return with pace on the break and nothing to lose."],
  ["kor","South Korea","🇰🇷","A",22,0,12,"Relentless pressing built around elite attacking transition."],
  ["cze","Czech Republic","🇨🇿","A",40,0,1,"Physical, set-piece savvy, and awkward to play against."],
  ["can","Canada","🇨🇦","B",28,0,3,"Co-hosts with frightening athleticism and a fearless young core."],
  ["bih","Bosnia & Herzegovina","🇧🇦","B",70,0,2,"Technically gifted spine chasing a golden-generation moment."],
  ["qat","Qatar","🇶🇦","B",53,0,2,"Patient possession side looking to rewrite their World Cup story."],
  ["sui","Switzerland","🇨🇭","B",17,0,13,"Organized, experienced, and quietly always in the knockouts."],
  ["bra","Brazil","🇧🇷","C",5,5,23,"The most successful team in World Cup history — flair, fearlessness, and a winning mentality."],
  ["mar","Morocco","🇲🇦","C",11,0,7,"2022 semifinalists — the best-organized defense outside Europe's elite."],
  ["hai","Haiti","🇭🇹","C",83,0,2,"Caribbean underdogs riding an emotional qualification wave."],
  ["sco","Scotland","🏴󠁧󠁢󠁳󠁣󠁴󠁿","C",38,0,9,"Back on the big stage with grit, atmosphere, and midfield bite."],
  ["usa","USA","🇺🇸","D",16,0,12,"Co-hosts with a prime-age core and genuine knockout ambitions."],
  ["par","Paraguay","🇵🇾","D",43,0,9,"Defensively ferocious — South America's great disruptors."],
  ["aus","Australia","🇦🇺","D",26,0,7,"The Socceroos: organized, brave, and better with the ball than ever."],
  ["tur","Türkiye","🇹🇷","D",27,0,3,"A golden generation of playmakers with tournament chaos in their DNA."],
  ["ger","Germany","🇩🇪","E",9,4,21,"Tournament specialists rebuilt around a young, ruthless midfield."],
  ["cuw","Curaçao","🇨🇼","E",90,0,1,"The smallest nation at the cup — and everyone's second team."],
  ["civ","Ivory Coast","🇨🇮","E",39,0,4,"African champions with power, pace, and a point to prove."],
  ["ecu","Ecuador","🇪🇨","E",24,0,5,"Altitude-forged engine room and the best young fullbacks around."],
  ["ned","Netherlands","🇳🇱","F",7,0,12,"Total-football heritage with a modern, pragmatic edge."],
  ["jpn","Japan","🇯🇵","F",18,0,8,"Europe-based core, lightning transitions, giant-killer pedigree."],
  ["swe","Sweden","🇸🇪","F",30,0,13,"Back after a decade — direct, physical, and dangerous in the air."],
  ["tun","Tunisia","🇹🇳","F",41,0,7,"Compact and disciplined — group-stage spoilers by trade."],
  ["bel","Belgium","🇧🇪","G",8,0,15,"Post-golden-generation reboot with elite talent in every line."],
  ["egy","Egypt","🇪🇬","G",33,0,4,"The Pharaohs follow their talisman — quality on the counter."],
  ["irn","Iran","🇮🇷","G",20,0,7,"Asia's most stubborn defense with real cutting edge up top."],
  ["nzl","New Zealand","🇳🇿","G",86,0,3,"Still unbeaten in World Cup history (3 draws in 2010) — seriously."],
  ["esp","Spain","🇪🇸","H",2,1,17,"European champions — suffocating possession and waves of young brilliance."],
  ["cpv","Cape Verde","🇨🇻","H",65,0,1,"Debutants with island flair and an electric counter-attack."],
  ["ksa","Saudi Arabia","🇸🇦","H",56,0,7,"Brave high line, home-league cohesion, Argentina-2022 scalp on the CV."],
  ["uru","Uruguay","🇺🇾","H",15,2,15,"Garra charrúa — two-time champions who never know they're beaten."],
  ["fra","France","🇫🇷","I",3,2,17,"Back-to-back finalists — frightening depth and a superstar ceiling."],
  ["sen","Senegal","🇸🇳","I",19,0,4,"Africa's most complete side: power, pace, and tournament know-how."],
  ["irq","Iraq","🇮🇶","I",58,0,2,"The Lions of Mesopotamia return after 40 years away."],
  ["nor","Norway","🇳🇴","I",32,0,4,"First cup since '98 — built around the most feared striker on earth."],
  ["arg","Argentina","🇦🇷","J",1,3,19,"Defending champions — streetwise, ferocious, and still hungry."],
  ["alg","Algeria","🇩🇿","J",36,0,5,"Desert Foxes with wing wizardry and a wounded-pride mission."],
  ["aut","Austria","🇦🇹","J",23,0,8,"The most aggressive pressing scheme at the tournament."],
  ["jor","Jordan","🇯🇴","J",68,0,1,"Asian Cup finalists making a historic first appearance."],
  ["por","Portugal","🇵🇹","K",6,0,9,"Nations League winners loaded with attacking riches across eras."],
  ["cod","DR Congo","🇨🇩","K",60,0,2,"The Leopards — athletic, fearless, and back after 52 years."],
  ["uzb","Uzbekistan","🇺🇿","K",62,0,1,"Debutants with the best youth pipeline in Asian football."],
  ["col","Colombia","🇨🇴","K",13,0,7,"Copa finalists — rhythm, flair, and a No.10 conducting everything."],
  ["eng","England","🏴󠁧󠁢󠁥󠁮󠁧󠁿","L",4,1,17,"Perennial contenders — a generational attack chasing the one that matters."],
  ["cro","Croatia","🇭🇷","L",10,0,7,"Finalists in '18, third in '22 — midfield royalty one last dance."],
  ["gha","Ghana","🇬🇭","L",54,0,5,"The Black Stars: direct, dynamic, and dangerous to anyone."],
  ["pan","Panama","🇵🇦","L",35,0,2,"CONCACAF's overachievers — compact and counter-punching."],
].map(a=>({id:a[0],name:a[1],flag:a[2],group:a[3],rank:a[4],titles:a[5],apps:a[6],summary:a[7]}));

export const TEAM = Object.fromEntries(T.map(t=>[t.id,t]));
export const GROUPS = "ABCDEFGHIJKL".split("").map(g=>({g,teams:T.filter(t=>t.group===g)}));

export const DETAILS = {
  bra:{style:"High-tempo 4-2-3-1 with inverted wingers and attacking fullbacks; relentless one-v-one threat wide.",
    strengths:"Depth of attacking talent, individual match-winners, set-piece delivery.",
    weaknesses:"Can be opened in transition when both fullbacks push; occasional knockout-round anxiety.",
    outlook:"Anything short of the semifinals is a failure — the squad believes hexa is on.",
    ptw:{n:"Vinícius Jr.",c:"Real Madrid",why:"Unplayable on his day — the tournament's biggest one-v-one mismatch."},
    bo:{n:"Estêvão",c:"Chelsea",why:"Teenage winger with the audacity to own the biggest stage."},
    coach:"Carlo Ancelotti",assts:["Davide Ancelotti","Paul Clement"],
    squad:[["GK","A. Becker","Liverpool",0],["GK","Bento","Al-Nassr",0],["DF","Marquinhos","PSG",1],["DF","G. Magalhães","Arsenal",0],["DF","É. Militão","Real Madrid",0],["DF","Danilo","Flamengo",0],["DF","Wendell","São Paulo",0],["MF","B. Guimarães","Newcastle",0],["MF","Casemiro","Man United",0],["MF","L. Paquetá","West Ham",0],["MF","Andreas Pereira","Fulham",0],["FW","Vinícius Jr.","Real Madrid",0],["FW","Rodrygo","Real Madrid",0],["FW","Raphinha","Barcelona",0],["FW","Estêvão","Chelsea",0],["FW","G. Jesus","Arsenal",0]]},
  arg:{style:"Champion's 4-3-3 — positional play with sudden vertical bursts and the game's smartest pressing triggers.",
    strengths:"Tournament temperament, midfield control, a dressing room that knows how to win.",
    weaknesses:"Aging spine in key positions; reliance on moments from their talisman.",
    outlook:"Title defense is real — nobody manages tournament pressure better.",
    ptw:{n:"Lionel Messi",c:"Inter Miami",why:"One last dance. Every touch will stop the stadium."},
    bo:{n:"Franco Mastantuono",c:"Real Madrid",why:"18-year-old playmaker already trusted in the biggest moments."},
    coach:"Lionel Scaloni",assts:["Pablo Aimar","Walter Samuel"],
    squad:[["GK","E. Martínez","Aston Villa",0],["DF","C. Romero","Tottenham",0],["DF","L. Martínez","Inter",0],["DF","N. Molina","Atlético Madrid",0],["DF","N. Tagliafico","Lyon",0],["MF","E. Fernández","Chelsea",0],["MF","A. Mac Allister","Liverpool",0],["MF","R. De Paul","Inter Miami",0],["MF","F. Mastantuono","Real Madrid",0],["FW","L. Messi","Inter Miami",1],["FW","J. Álvarez","Atlético Madrid",0],["FW","L. Martínez","Inter",0],["FW","N. González","Juventus",0]]},
  fra:{style:"Devastating 4-3-3 transition machine — soak pressure, then strike in four passes or fewer.",
    strengths:"Two world-class options per position; the best counter-attack in international football.",
    weaknesses:"Can drift through group games; midfield creativity depends on form.",
    outlook:"Third final in a row is genuinely on the table.",
    ptw:{n:"Kylian Mbappé",c:"Real Madrid",why:"The face of the tournament — chasing the Golden Boot and redemption."},
    bo:{n:"Désiré Doué",c:"PSG",why:"Champions-League-final hero ready to detonate on the world stage."},
    coach:"Didier Deschamps",assts:["Guy Stéphan","Franck Raviot"],
    squad:[["GK","M. Maignan","AC Milan",0],["DF","W. Saliba","Arsenal",0],["DF","I. Konaté","Liverpool",0],["DF","T. Hernández","Al-Hilal",0],["DF","J. Koundé","Barcelona",0],["MF","A. Tchouaméni","Real Madrid",0],["MF","E. Camavinga","Real Madrid",0],["MF","M. Zaïre-Emery","PSG",0],["FW","K. Mbappé","Real Madrid",1],["FW","O. Dembélé","PSG",0],["FW","D. Doué","PSG",0],["FW","M. Olise","Bayern Munich",0]]},
  eng:{style:"Patient build-up 4-2-3-1 that flips ruthless once the press is broken; elite dead-ball threat.",
    strengths:"Arguably the deepest attacking pool in the tournament; settled keeper and back line.",
    weaknesses:"History of conservative big-game management; left-back remains a question.",
    outlook:"It might actually be coming home — quarterfinals are the floor, not the ceiling.",
    ptw:{n:"Jude Bellingham",c:"Real Madrid",why:"Box-to-box royalty who lives for the decisive moment."},
    bo:{n:"Myles Lewis-Skelly",c:"Arsenal",why:"Fearless teenager who's made the impossible look routine."},
    coach:"Thomas Tuchel",assts:["Anthony Barry"],
    squad:[["GK","J. Pickford","Everton",0],["DF","J. Stones","Man City",0],["DF","M. Guéhi","Liverpool",0],["DF","T. Alexander-Arnold","Real Madrid",0],["DF","M. Lewis-Skelly","Arsenal",0],["MF","D. Rice","Arsenal",0],["MF","J. Bellingham","Real Madrid",0],["MF","C. Palmer","Chelsea",0],["FW","H. Kane","Bayern Munich",1],["FW","B. Saka","Arsenal",0],["FW","P. Foden","Man City",0],["FW","A. Gordon","Newcastle",0]]},
  ger:{style:"Brave 4-2-3-1 with a high line, vertical passing through the lines, and ruthless set pieces.",
    strengths:"Midfield technicians, tournament pedigree, home-from-home support in the US.",
    weaknesses:"Striker question never fully answered; vulnerable to elite pace in behind.",
    outlook:"Rebuilt and dangerous — a semifinal run would surprise nobody.",
    ptw:{n:"Jamal Musiala",c:"Bayern Munich",why:"The slalom dribbler defenses simply cannot plan for."},
    bo:{n:"Florian Wirtz",c:"Liverpool",why:"Already world-class — this is the tournament the world finds out."},
    coach:"Julian Nagelsmann",assts:["Sandro Wagner","Benjamin Glück"],
    squad:[["GK","M. ter Stegen","Barcelona",0],["DF","A. Rüdiger","Real Madrid",0],["DF","J. Tah","Bayern Munich",0],["DF","J. Kimmich","Bayern Munich",1],["DF","D. Raum","RB Leipzig",0],["MF","Pavlović","Bayern Munich",0],["MF","F. Wirtz","Liverpool",0],["MF","J. Musiala","Bayern Munich",0],["FW","K. Havertz","Arsenal",0],["FW","L. Sané","Galatasaray",0],["FW","N. Woltemade","Newcastle",0]]},
  esp:{style:"Positional-play 4-3-3 — suffocate with possession, stretch you with wingers, strike through half-spaces.",
    strengths:"Best midfield on the planet; tactical clarity; winners' habit from Euro 2024.",
    weaknesses:"Lack of a true target man; can over-pass against deep blocks.",
    outlook:"Tournament favorites alongside Argentina and France.",
    ptw:{n:"Lamine Yamal",c:"Barcelona",why:"18 and already the most-watched footballer alive."},
    bo:{n:"Pau Cubarsí",c:"Barcelona",why:"Teen center-back who defends like he's seen everything twice."},
    coach:"Luis de la Fuente",assts:["Pablo Amo"],
    squad:[["GK","U. Simón","Athletic Club",0],["DF","P. Cubarsí","Barcelona",0],["DF","R. Le Normand","Atlético Madrid",0],["DF","M. Cucurella","Chelsea",0],["DF","D. Carvajal","Real Madrid",0],["MF","Rodri","Man City",1],["MF","Pedri","Barcelona",0],["MF","F. Ruiz","PSG",0],["FW","L. Yamal","Barcelona",0],["FW","N. Williams","Athletic Club",0],["FW","M. Oyarzabal","Real Sociedad",0]]},
  usa:{style:"Energetic 4-3-3 pressing scheme with overlapping fullbacks and quick wide combinations.",
    strengths:"Athleticism, home crowds in 11 cities, a core finally in its prime together.",
    weaknesses:"Striker production; tendency to sit back protecting leads.",
    outlook:"The quarterfinal barrier is the mission — and at home, it's possible.",
    ptw:{n:"Christian Pulisic",c:"AC Milan",why:"Captain America, in form, in front of home crowds."},
    bo:{n:"Diego Luna",c:"Real Salt Lake",why:"Fearless creator who plays every game like a street final."},
    coach:"Mauricio Pochettino",assts:["Jesús Pérez","Miguel D'Agostino"],
    squad:[["GK","M. Turner","Lyon",0],["DF","C. Richards","Crystal Palace",0],["DF","A. Robinson","Fulham",0],["DF","S. Dest","PSV",0],["MF","T. Adams","Bournemouth",1],["MF","W. McKennie","Juventus",0],["MF","Y. Musah","Atalanta",0],["FW","C. Pulisic","AC Milan",0],["FW","T. Weah","Marseille",0],["FW","F. Balogun","Monaco",0],["FW","D. Luna","Real Salt Lake",0]]},
  mex:{style:"Front-foot 4-3-3 with wide overloads and the loudest twelfth man at the tournament.",
    strengths:"Home advantage at altitude, tournament-opening momentum, midfield craft.",
    weaknesses:"Finishing droughts; pressure of hosting weighs heavy.",
    outlook:"Breaking the round-of-16 curse at home would make this a historic summer.",
    ptw:{n:"Santiago Giménez",c:"AC Milan",why:"The No.9 Mexico has waited a generation for."},
    bo:{n:"Gilberto Mora",c:"Tijuana",why:"17-year-old playmaker with the Azteca ready to crown him."},
    coach:"Javier Aguirre",assts:["Rafael Márquez"],
    squad:[["GK","L. Malagón","América",0],["DF","C. Montes","Lokomotiv",0],["DF","J. Vásquez","Genoa",0],["DF","J. Gallardo","Toluca",0],["MF","E. Álvarez","West Ham",1],["MF","L. Chávez","Dynamo Moscow",0],["MF","G. Mora","Tijuana",0],["FW","S. Giménez","AC Milan",0],["FW","H. Lozano","San Diego FC",0],["FW","A. Vega","Toluca",0]]},
};
