// 48 teams · groups per the official draw layout used in the design reference.
// rank / titles / appearances / squads are editable sample data.
export const T = [

  ["mex","Mexico","🇲🇽","A",14,0,18,"Home advantage, renewed momentum and tactical stability under Javier Aguirre — a strong chance of topping Group A."],
  ["rsa","South Africa","🇿🇦","A",59,0,4,"Built on chemistry and team spirit under Hugo Broos — cohesive underdogs despite recent struggles."],
  ["kor","South Korea","🇰🇷","A",22,0,12,"Arguably the strongest squad on paper in Group A — elite talent shadowed by tactical uncertainty and inconsistent recent form."],
  ["cze","Czechia","🇨🇿","A",40,0,1,"Organised and set-piece savvy, arriving in excellent form after a dramatic qualification — Patrik Schick leads the line."],
  ["can","Canada","🇨🇦","B",28,0,3,"Athletic, high-intensity football under Jesse Marsch — Alphonso Davies and Jonathan David lead the pace, pressing and home support."],
  ["bih","Bosnia & Herzegovina","🇧🇦","B",70,0,2,"Surprise qualifiers with an experienced core — veterans like Edin Džeko and Sead Kolašinac alongside emerging talent."],
  ["qat","Qatar","🇶🇦","B",53,0,2,"Technically capable and out to prove they belong, building on recent major-tournament experience — questions remain over depth."],
  ["sui","Switzerland","🇨🇭","B",17,0,13,"The group's most established side — balanced squad, strong organisation, and a habit of reaching the knockouts."],
  ["bra","Brazil","🇧🇷","C",5,5,23,"Elite attacking talent and Carlo Ancelotti's leadership — genuine challengers for the World Cup title."],
  ["mar","Morocco","🇲🇦","C",11,0,7,"A deeper, more complete squad than the 2022 semi-finalists — established stars blended with elite young talent."],
  ["hai","Haiti","🇭🇹","C",83,0,2,"Back at the World Cup after a long absence — direct, energetic and motivated, strengthened by dual-national recruits."],
  ["sco","Scotland","🏴󠁧󠁢󠁳󠁣󠁴󠁿","C",38,0,9,"Built on chemistry, midfield quality and years of continuity — realistic contenders to reach the knockout stages."],
  ["usa","USA","🇺🇸","D",16,0,12,"Co-hosts with a prime-age core and genuine knockout ambitions."],
  ["par","Paraguay","🇵🇾","D",43,0,9,"Defensively ferocious — South America's great disruptors."],
  ["aus","Australia","🇦🇺","D",26,0,7,"The Socceroos: organized, brave, and better with the ball than ever."],
  ["tur","Türkiye","🇹🇷","D",27,0,3,"A golden generation of playmakers with tournament chaos in their DNA."],
  ["ger","Germany","🇩🇪","E",9,4,21,"Tournament specialists rebuilt around a young, ruthless midfield."],
  ["cuw","Curaçao","🇨🇼","E",90,0,1,"The smallest nation at the cup — and everyone's second team."],
  ["civ","Ivory Coast","🇨🇮","E",39,0,4,"African champions with power, pace, and a point to prove."],
  ["ecu","Ecuador","🇪🇨","E",24,0,5,"Altitude-forged engine room and the best young fullbacks around."],
  ["ned","Netherlands","🇳🇱","F",7,0,12,"Total-football heritage with a modern, pragmatic edge."],
  ["jpn","Japan","🇯🇵","F",18,0,8,"Europe-based core, lightning transitions, giant-killer pedigree."],
  ["swe","Sweden","🇸🇪","F",30,0,13,"Back after a decade — direct, physical, and dangerous in the air."],
  ["tun","Tunisia","🇹🇳","F",41,0,7,"Compact and disciplined — group-stage spoilers by trade."],
  ["bel","Belgium","🇧🇪","G",8,0,15,"Post-golden-generation reboot with elite talent in every line."],
  ["egy","Egypt","🇪🇬","G",33,0,4,"The Pharaohs follow their talisman — quality on the counter."],
  ["irn","Iran","🇮🇷","G",20,0,7,"Asia's most stubborn defense with real cutting edge up top."],
  ["nzl","New Zealand","🇳🇿","G",86,0,3,"Still unbeaten in World Cup history (3 draws in 2010) — seriously."],
  ["esp","Spain","🇪🇸","H",2,1,17,"European champions — suffocating possession and waves of young brilliance."],
  ["cpv","Cape Verde","🇨🇻","H",65,0,1,"Debutants with island flair and an electric counter-attack."],
  ["ksa","Saudi Arabia","🇸🇦","H",56,0,7,"Brave high line, home-league cohesion, Argentina-2022 scalp on the CV."],
  ["uru","Uruguay","🇺🇾","H",15,2,15,"Garra charrúa — two-time champions who never know they're beaten."],
  ["fra","France","🇫🇷","I",3,2,17,"Back-to-back finalists — frightening depth and a superstar ceiling."],
  ["sen","Senegal","🇸🇳","I",19,0,4,"Africa's most complete side: power, pace, and tournament know-how."],
  ["irq","Iraq","🇮🇶","I",58,0,2,"The Lions of Mesopotamia return after 40 years away."],
  ["nor","Norway","🇳🇴","I",32,0,4,"First cup since '98 — built around the most feared striker on earth."],
  ["arg","Argentina","🇦🇷","J",1,3,19,"Defending champions — streetwise, ferocious, and still hungry."],
  ["alg","Algeria","🇩🇿","J",36,0,5,"Desert Foxes with wing wizardry and a wounded-pride mission."],
  ["aut","Austria","🇦🇹","J",23,0,8,"The most aggressive pressing scheme at the tournament."],
  ["jor","Jordan","🇯🇴","J",68,0,1,"Asian Cup finalists making a historic first appearance."],
  ["por","Portugal","🇵🇹","K",6,0,9,"Nations League winners loaded with attacking riches across eras."],
  ["cod","DR Congo","🇨🇩","K",60,0,2,"The Leopards — athletic, fearless, and back after 52 years."],
  ["uzb","Uzbekistan","🇺🇿","K",62,0,1,"Debutants with the best youth pipeline in Asian football."],
  ["col","Colombia","🇨🇴","K",13,0,7,"Copa finalists — rhythm, flair, and a No.10 conducting everything."],
  ["eng","England","🏴󠁧󠁢󠁥󠁮󠁧󠁿","L",4,1,17,"Perennial contenders — a generational attack chasing the one that matters."],
  ["cro","Croatia","🇭🇷","L",10,0,7,"Finalists in '18, third in '22 — midfield royalty one last dance."],
  ["gha","Ghana","🇬🇭","L",54,0,5,"The Black Stars: direct, dynamic, and dangerous to anyone."],
  ["pan","Panama","🇵🇦","L",35,0,2,"CONCACAF's overachievers — compact and counter-punching."],
].map(a=>({id:a[0],name:a[1],flag:a[2],group:a[3],rank:a[4],titles:a[5],apps:a[6],summary:a[7]}));

export const TEAM = Object.fromEntries(T.map(t=>[t.id,t]));
export const GROUPS = "ABCDEFGHIJKL".split("").map(g=>({g,teams:T.filter(t=>t.group===g)}));

export const DETAILS = {
  rsa:{intro:"South Africa return to the World Cup for the first time since 2010. The squad is built around chemistry and continuity, with many players developed and still playing domestically.",
    style:"A disciplined 4-2-3-1 structure with a team-first approach, relying on chemistry and work rate.",
    strengths:"Strong team spirit, continuity under Hugo Broos, local chemistry, and growing belief following AFCON performances.",
    weaknesses:"Poor recent results, limited international experience, administrative issues, and a lack of elite-level depth.",
    outlook:"Underdogs capable of surprising teams through organisation and collective belief.",
    keyPlayers:["Teboho Mokoena","Ronwen Williams","Siyabonga Ngezana","Relebohile Mofokeng","Lyle Foster"],
    coach:"Hugo Broos"},
  kor:{intro:"South Korea possess one of the most talented squads in the group but enter with concerns surrounding form and tactical changes.",
    style:"A shift from a back four to a 3-4-3, with technical quality across the squad, attacking intent, and a flexible midfield structure.",
    strengths:"Elite individual talent, experience, technical quality, and an established core.",
    weaknesses:"Recent heavy defeats, defensive instability, uncertainty surrounding the new system, and key players arriving out of form.",
    outlook:"Capable of winning the group but difficult to predict due to recent performances.",
    keyPlayers:["Son Heung-min","Kim Min-jae","Lee Kang-in","Hwang In-beom","Lee Jae-sung","Jens Castrop"]},
  cze:{intro:"Returning to the World Cup for the first time since 2006, Czechia arrive with confidence after navigating a dramatic qualification journey.",
    style:"Physical and organised with direct attacking football, a strong set-piece threat, and tactical discipline.",
    strengths:"Momentum, set pieces, an experienced spine, and a reliable goalscorer in Schick.",
    weaknesses:"Reliance on Schick for goals, limited creativity outside key players, and less depth than some rivals.",
    outlook:"One of the dark horses in the group and a genuine contender for qualification.",
    keyPlayers:["Patrik Schick","Pavel Šulc","Tomáš Souček","Tomáš Holeš","Vladimír Coufal"]},
  sui:{intro:"Switzerland remain one of the most dependable tournament teams in international football. They consistently reach knockout rounds and rarely underperform.",
    style:"An organised defensive structure with efficient possession, strong midfield partnerships, and tactical discipline.",
    strengths:"Experience, squad continuity, strong defensive partnerships, and the ability to consistently beat lower-ranked opponents.",
    weaknesses:"An ageing core in certain areas and the lack of a prolific elite striker.",
    outlook:"Strong favourites to top the group.",
    keyPlayers:["Manuel Akanji","Nico Elvedi","Granit Xhaka","Remo Freuler","Ardon Jashari","Noah Okafor","Breel Embolo"]},
  can:{intro:"Canada arrive as arguably the most settled of the host nations. Jesse Marsch has implemented an energetic, high-intensity style that suits the athletic profile of the squad.",
    style:"High pressing and vertical attacking football — Red Bull-inspired intensity with fast transitions.",
    strengths:"Athleticism, home support, a clear tactical identity, and attacking pace.",
    weaknesses:"Defensive consistency, goalkeeper questions, and several key players not arriving in peak form.",
    outlook:"Strong contender for second place and knockout qualification.",
    keyPlayers:["Alphonso Davies","Jonathan David","Promise David","Ismaël Koné","Stephen Eustáquio","Tajon Buchanan","Liam Millar"],
    coach:"Jesse Marsch"},
  bih:{intro:"Bosnia & Herzegovina are one of the surprise qualifiers after overcoming Wales and Italy in the playoffs.",
    style:"A compact defensive structure with direct football, an experience-led approach, and a threat from wide areas.",
    strengths:"Leadership, defensive resilience, and exciting young talent emerging alongside experienced veterans.",
    weaknesses:"An inexperienced midfield and a lack of depth compared to rivals.",
    outlook:"Capable of challenging for qualification and difficult to break down.",
    keyPlayers:["Edin Džeko","Sead Kolašinac","Amar Dedić","Muharemović","Bajraktarević","Ali Begović"]},
  qat:{intro:"Qatar return to the World Cup after hosting the previous edition. The squad is highly familiar with one another due to the domestic-based nature of the group.",
    style:"Structured defensive football with patient build-up, relying on chemistry and familiarity.",
    strengths:"Experience together, strong understanding between players, and familiarity with tournament football.",
    weaknesses:"An ageing squad, limited depth, and a lack of players competing in top European leagues.",
    outlook:"Likely outsiders but capable of making games difficult through organisation.",
    keyPlayers:["Akram Afif","Almoez Ali","Hassan Al-Haydos"]},
  mar:{intro:"Morocco arrive with a deeper squad than the team that reached the 2022 semi-finals and are viewed as one of the strongest dark horses in the tournament.",
    style:"Organised defending with dangerous transitions, strong wide play, and a technically gifted midfield.",
    strengths:"Depth, balance between youth and experience, and quality across multiple positions.",
    weaknesses:"Pressure created by increased expectations and a relatively new coaching setup.",
    outlook:"Capable of another deep knockout run.",
    keyPlayers:["Achraf Hakimi","Bilal El Khannouss","Ismael Saibari","Ayyoub Bouaddi","Abde Ezzalzouli","Brahim Díaz","Ayoub El Kaabi"]},
  hai:{intro:"Haiti return to the World Cup for the first time since 1974 and arrive after successfully recruiting a number of dual-nationality players.",
    style:"Direct football with vertical attacks and a counter-attacking approach.",
    strengths:"Athleticism, motivation, an improving talent pool, and a direct style.",
    weaknesses:"Limited World Cup experience, squad cohesion, and depth compared to rivals.",
    outlook:"Outsiders, but capable of troubling stronger teams.",
    keyPlayers:["Wilson Isidor","Jean-Ricner Bellegarde","Danley Jean Jacques","Frantzdy Pierrot","Duckens Nazon"]},
  sco:{intro:"Scotland arrive with momentum after an emotional qualification campaign and rely heavily on continuity and team chemistry.",
    style:"A structured, midfield-driven approach with wing-backs providing width and a strong collective identity.",
    strengths:"Chemistry, leadership, midfield quality, and experience playing together.",
    weaknesses:"Lack of elite goalscorers, defensive depth, and injuries in key areas.",
    outlook:"Strong candidate to challenge for qualification, particularly through a best third-place route.",
    keyPlayers:["Scott McTominay","John McGinn","Ryan Christie","Andy Robertson","Aaron Hickey","Ross Stewart"]},

  bra:{intro:"Brazil arrive with enormous talent and Carlo Ancelotti in charge. They remain one of the most feared teams in the competition.",
    keyPlayers:["Vinícius Júnior","Raphinha","Neymar","Casemiro","Bremer","Gabriel","Endrick"],
    style:"Attacking football with positional freedom, a fluid front line, and an emphasis on creativity.",
    strengths:"Elite attacking depth, experience, a world-class manager, and game-changing individuals.",
    weaknesses:"Full-back depth, midfield balance, and defensive transitions.",
    outlook:"Potential title challengers capable of reaching the latter stages.",
    ptw:{n:"Vinícius Jr.",c:"Real Madrid",why:"Unplayable on his day — the tournament's biggest one-v-one mismatch."},
    bo:{n:"Estêvão",c:"Chelsea",why:"Teenage winger with the audacity to own the biggest stage."},
    coach:"Carlo Ancelotti",assts:["Davide Ancelotti","Paul Clement"],
    squad:[["GK","A. Becker","Liverpool",0],["GK","Bento","Al-Nassr",0],["DF","Marquinhos","PSG",1],["DF","G. Magalhães","Arsenal",0],["DF","É. Militão","Real Madrid",0],["DF","Danilo","Flamengo",0],["DF","Wendell","São Paulo",0],["MF","B. Guimarães","Newcastle",0],["MF","Casemiro","Man United",0],["MF","L. Paquetá","West Ham",0],["MF","Andreas Pereira","Fulham",0],["FW","Vinícius Jr.","Real Madrid",0],["FW","Rodrygo","Real Madrid",0],["FW","Raphinha","Barcelona",0],["FW","Estêvão","Chelsea",0],["FW","G. Jesus","Arsenal",0]]},
  arg:{style:"Champion's 4-3-3 — positional play with sudden vertical bursts and the game's smartest pressing triggers.",
    strengths:"Tournament temperament, midfield control, a dressing room that knows how to win.",
    weaknesses:"Aging spine in key positions; reliance on moments from their talisman.",
    outlook:"Title defense is real — nobody manages tournament pressure better.",
    ptw:{n:"Lionel Messi",c:"Inter Miami",why:"One last dance. Every touch will stop the stadium."},
    bo:{n:"Franco Mastantuono",c:"Real Madrid",why:"18-year-old playmaker already trusted in the biggest moments."},
    coach:"Lionel Scaloni",assts:["Pablo Aimar","Walter Samuel"],
    squad:[["GK","E. Martínez","Aston Villa",0],["DF","C. Romero","Tottenham",0],["DF","L. Martínez","Inter",0],["DF","N. Molina","Atlético Madrid",0],["DF","N. Tagliafico","Lyon",0],["MF","E. Fernández","Chelsea",0],["MF","A. Mac Allister","Liverpool",0],["MF","R. De Paul","Inter Miami",0],["MF","F. Mastantuono","Real Madrid",0],["FW","L. Messi","Inter Miami",1],["FW","J. Álvarez","Atlético Madrid",0],["FW","L. Martínez","Inter",0],["FW","N. González","Juventus",0]]},
  fra:{style:"Devastating 4-3-3 transition machine — soak pressure, then strike in four passes or fewer.",
    strengths:"Two world-class options per position; the best counter-attack in international football.",
    weaknesses:"Can drift through group games; midfield creativity depends on form.",
    outlook:"Third final in a row is genuinely on the table.",
    ptw:{n:"Kylian Mbappé",c:"Real Madrid",why:"The face of the tournament — chasing the Golden Boot and redemption."},
    bo:{n:"Désiré Doué",c:"PSG",why:"Champions-League-final hero ready to detonate on the world stage."},
    coach:"Didier Deschamps",assts:["Guy Stéphan","Franck Raviot"],
    squad:[["GK","M. Maignan","AC Milan",0],["DF","W. Saliba","Arsenal",0],["DF","I. Konaté","Liverpool",0],["DF","T. Hernández","Al-Hilal",0],["DF","J. Koundé","Barcelona",0],["MF","A. Tchouaméni","Real Madrid",0],["MF","E. Camavinga","Real Madrid",0],["MF","M. Zaïre-Emery","PSG",0],["FW","K. Mbappé","Real Madrid",1],["FW","O. Dembélé","PSG",0],["FW","D. Doué","PSG",0],["FW","M. Olise","Bayern Munich",0]]},
  eng:{style:"Patient build-up 4-2-3-1 that flips ruthless once the press is broken; elite dead-ball threat.",
    strengths:"Arguably the deepest attacking pool in the tournament; settled keeper and back line.",
    weaknesses:"History of conservative big-game management; left-back remains a question.",
    outlook:"It might actually be coming home — quarterfinals are the floor, not the ceiling.",
    ptw:{n:"Jude Bellingham",c:"Real Madrid",why:"Box-to-box royalty who lives for the decisive moment."},
    bo:{n:"Myles Lewis-Skelly",c:"Arsenal",why:"Fearless teenager who's made the impossible look routine."},
    coach:"Thomas Tuchel",assts:["Anthony Barry"],
    squad:[["GK","J. Pickford","Everton",0],["DF","J. Stones","Man City",0],["DF","M. Guéhi","Liverpool",0],["DF","T. Alexander-Arnold","Real Madrid",0],["DF","M. Lewis-Skelly","Arsenal",0],["MF","D. Rice","Arsenal",0],["MF","J. Bellingham","Real Madrid",0],["MF","C. Palmer","Chelsea",0],["FW","H. Kane","Bayern Munich",1],["FW","B. Saka","Arsenal",0],["FW","P. Foden","Man City",0],["FW","A. Gordon","Newcastle",0]]},
  ger:{style:"Brave 4-2-3-1 with a high line, vertical passing through the lines, and ruthless set pieces.",
    strengths:"Midfield technicians, tournament pedigree, home-from-home support in the US.",
    weaknesses:"Striker question never fully answered; vulnerable to elite pace in behind.",
    outlook:"Rebuilt and dangerous — a semifinal run would surprise nobody.",
    ptw:{n:"Jamal Musiala",c:"Bayern Munich",why:"The slalom dribbler defenses simply cannot plan for."},
    bo:{n:"Florian Wirtz",c:"Liverpool",why:"Already world-class — this is the tournament the world finds out."},
    coach:"Julian Nagelsmann",assts:["Sandro Wagner","Benjamin Glück"],
    squad:[["GK","M. ter Stegen","Barcelona",0],["DF","A. Rüdiger","Real Madrid",0],["DF","J. Tah","Bayern Munich",0],["DF","J. Kimmich","Bayern Munich",1],["DF","D. Raum","RB Leipzig",0],["MF","Pavlović","Bayern Munich",0],["MF","F. Wirtz","Liverpool",0],["MF","J. Musiala","Bayern Munich",0],["FW","K. Havertz","Arsenal",0],["FW","L. Sané","Galatasaray",0],["FW","N. Woltemade","Newcastle",0]]},
  esp:{style:"Positional-play 4-3-3 — suffocate with possession, stretch you with wingers, strike through half-spaces.",
    strengths:"Best midfield on the planet; tactical clarity; winners' habit from Euro 2024.",
    weaknesses:"Lack of a true target man; can over-pass against deep blocks.",
    outlook:"Tournament favorites alongside Argentina and France.",
    ptw:{n:"Lamine Yamal",c:"Barcelona",why:"18 and already the most-watched footballer alive."},
    bo:{n:"Pau Cubarsí",c:"Barcelona",why:"Teen center-back who defends like he's seen everything twice."},
    coach:"Luis de la Fuente",assts:["Pablo Amo"],
    squad:[["GK","U. Simón","Athletic Club",0],["DF","P. Cubarsí","Barcelona",0],["DF","R. Le Normand","Atlético Madrid",0],["DF","M. Cucurella","Chelsea",0],["DF","D. Carvajal","Real Madrid",0],["MF","Rodri","Man City",1],["MF","Pedri","Barcelona",0],["MF","F. Ruiz","PSG",0],["FW","L. Yamal","Barcelona",0],["FW","N. Williams","Athletic Club",0],["FW","M. Oyarzabal","Real Sociedad",0]]},
  usa:{style:"Energetic 4-3-3 pressing scheme with overlapping fullbacks and quick wide combinations.",
    strengths:"Athleticism, home crowds in 11 cities, a core finally in its prime together.",
    weaknesses:"Striker production; tendency to sit back protecting leads.",
    outlook:"The quarterfinal barrier is the mission — and at home, it's possible.",
    ptw:{n:"Christian Pulisic",c:"AC Milan",why:"Captain America, in form, in front of home crowds."},
    bo:{n:"Diego Luna",c:"Real Salt Lake",why:"Fearless creator who plays every game like a street final."},
    coach:"Mauricio Pochettino",assts:["Jesús Pérez","Miguel D'Agostino"],
    squad:[["GK","M. Turner","Lyon",0],["DF","C. Richards","Crystal Palace",0],["DF","A. Robinson","Fulham",0],["DF","S. Dest","PSV",0],["MF","T. Adams","Bournemouth",1],["MF","W. McKennie","Juventus",0],["MF","Y. Musah","Atalanta",0],["FW","C. Pulisic","AC Milan",0],["FW","T. Weah","Marseille",0],["FW","F. Balogun","Monaco",0],["FW","D. Luna","Real Salt Lake",0]]},
  mex:{intro:"Mexico enter the World Cup looking to erase the disappointment of their 2022 group-stage exit. Under Javier Aguirre, they have become more organised, pragmatic, and tactically flexible.",
    keyPlayers:["Edson Álvarez","Santiago Giménez","Raúl Jiménez","Johan Vásquez","César Montes","Gilberto Mora","Álvaro Fidalgo"],
    style:"Direct transitions with wingers moving into central areas and full-backs providing width — a structured defensive shape, less possession-focused than previous Mexico teams.",
    strengths:"Home advantage, strong recent form, tactical clarity, an experienced defensive core, and growing confidence.",
    weaknesses:"Goalkeeper uncertainty, lack of elite attacking creativity, pressure from supporters, and dependence on key attackers finding form.",
    outlook:"Mexico have a strong chance of topping the group and returning to the knockout rounds.",
    ptw:{n:"Santiago Giménez",c:"AC Milan",why:"The No.9 Mexico has waited a generation for."},
    bo:{n:"Gilberto Mora",c:"Tijuana",why:"17-year-old playmaker with the Azteca ready to crown him."},
    coach:"Javier Aguirre",assts:["Rafael Márquez"],
    squad:[["GK","L. Malagón","América",0],["DF","C. Montes","Lokomotiv",0],["DF","J. Vásquez","Genoa",0],["DF","J. Gallardo","Toluca",0],["MF","E. Álvarez","West Ham",1],["MF","L. Chávez","Dynamo Moscow",0],["MF","G. Mora","Tijuana",0],["FW","S. Giménez","AC Milan",0],["FW","H. Lozano","San Diego FC",0],["FW","A. Vega","Toluca",0]]},
};

// Group overviews — written by the site editor. Add more groups as content arrives.
export const GROUP_OVERVIEWS = {
  A: "Group A is one of the most open groups in the tournament. Mexico arrive with home advantage and renewed confidence under Javier Aguirre, South Korea possess the strongest collection of individual talent, Czechia enter the competition with momentum after a dramatic qualification campaign, and South Africa bring continuity, chemistry, and belief. No team enters as a clear favourite, making every match potentially decisive.",
  B: "Group B combines tournament experience, home support, underdog resilience, and an ambitious Qatar side. Switzerland enter as favourites, Canada appear the most settled host nation, Bosnia & Herzegovina arrive with momentum after dramatic qualification, and Qatar rely on familiarity and experience.",
  C: "Group C contains one of the tournament favourites, one of the strongest dark horses, an inspiring underdog story, and a Scotland side seeking to build on a memorable qualification campaign.",
};
