// 48 teams · groups per the official draw layout used in the design reference.
// rank / titles / appearances / squads are editable sample data.
export const T = [

  ["mex","Mexico","🇲🇽","A",14,0,18,"Home advantage, renewed momentum and tactical stability under Javier Aguirre — a strong chance of topping Group A."],
  ["rsa","South Africa","🇿🇦","A",59,0,4,"Built on chemistry and team spirit under Hugo Broos — cohesive underdogs despite recent struggles."],
  ["kor","South Korea","🇰🇷","A",22,0,12,"Arguably the strongest squad on paper in Group A — elite talent shadowed by tactical uncertainty and inconsistent recent form."],
  ["cze","Czechia","🇨🇿","A",40,0,1,"Organised and set-piece savvy, arriving in excellent form after a dramatic qualification — Patrik Schick leads the line."],
  ["can","Canada","🇨🇦","B",28,0,3,"Athletic, high-intensity football under Jesse Marsch — Alphonso Davies and Jonathan David lead the pace, pressing and home support."],
  ["bih","Bosnia & Herzegovina","🇧🇦","B",70,0,2,"Surprise qualifiers with an experienced core — veterans like Edin Džeko and Sead Kolašinac alongside emerging talent."],
  ["qat","Qatar","🇶🇦","B",53,0,2,"Technically capable and out to prove they belong, building on recent major-tournament experience — questions remain over depth."],
  ["sui","Switzerland","🇨🇭","B",17,0,13,"The group's most established side — balanced squad, strong organisation, and a habit of reaching the knockouts."],
  ["bra","Brazil","🇧🇷","C",5,5,23,"Elite attacking talent and Carlo Ancelotti's leadership — genuine challengers for the World Cup title."],
  ["mar","Morocco","🇲🇦","C",11,0,7,"A deeper, more complete squad than the 2022 semi-finalists — established stars blended with elite young talent."],
  ["hai","Haiti","🇭🇹","C",83,0,2,"Back at the World Cup after a long absence — direct, energetic and motivated, strengthened by dual-national recruits."],
  ["sco","Scotland","🏴󠁧󠁢󠁳󠁣󠁴󠁿","C",38,0,9,"Built on chemistry, midfield quality and years of continuity — realistic contenders to reach the knockout stages."],
  ["usa","USA","🇺🇸","D",16,0,12,"Co-hosts with a prime-age core and genuine knockout ambitions."],
  ["par","Paraguay","🇵🇾","D",43,0,9,"Defensively ferocious — South America's great disruptors."],
  ["aus","Australia","🇦🇺","D",26,0,7,"The Socceroos: organized, brave, and better with the ball than ever."],
  ["tur","Türkiye","🇹🇷","D",27,0,3,"A golden generation of playmakers with tournament chaos in their DNA."],
  ["ger","Germany","🇩🇪","E",9,4,21,"Tournament specialists rebuilt around a young, ruthless midfield."],
  ["cuw","Curaçao","🇨🇼","E",90,0,1,"The smallest nation at the cup — and everyone's second team."],
  ["civ","Ivory Coast","🇨🇮","E",39,0,4,"African champions with power, pace, and a point to prove."],
  ["ecu","Ecuador","🇪🇨","E",24,0,5,"Altitude-forged engine room and the best young fullbacks around."],
  ["ned","Netherlands","🇳🇱","F",7,0,12,"Total-football heritage with a modern, pragmatic edge."],
  ["jpn","Japan","🇯🇵","F",18,0,8,"Europe-based core, lightning transitions, giant-killer pedigree."],
  ["swe","Sweden","🇸🇪","F",30,0,13,"Back after a decade — direct, physical, and dangerous in the air."],
  ["tun","Tunisia","🇹🇳","F",41,0,7,"Compact and disciplined — group-stage spoilers by trade."],
  ["bel","Belgium","🇧🇪","G",8,0,15,"Post-golden-generation reboot with elite talent in every line."],
  ["egy","Egypt","🇪🇬","G",33,0,4,"The Pharaohs follow their talisman — quality on the counter."],
  ["irn","Iran","🇮🇷","G",20,0,7,"Asia's most stubborn defense with real cutting edge up top."],
  ["nzl","New Zealand","🇳🇿","G",86,0,3,"Still unbeaten in World Cup history (3 draws in 2010) — seriously."],
  ["esp","Spain","🇪🇸","H",2,1,17,"European champions — suffocating possession and waves of young brilliance."],
  ["cpv","Cape Verde","🇨🇻","H",65,0,1,"Debutants with island flair and an electric counter-attack."],
  ["ksa","Saudi Arabia","🇸🇦","H",56,0,7,"Brave high line, home-league cohesion, Argentina-2022 scalp on the CV."],
  ["uru","Uruguay","🇺🇾","H",15,2,15,"Garra charrúa — two-time champions who never know they're beaten."],
  ["fra","France","🇫🇷","I",3,2,17,"Back-to-back finalists — frightening depth and a superstar ceiling."],
  ["sen","Senegal","🇸🇳","I",19,0,4,"Africa's most complete side: power, pace, and tournament know-how."],
  ["irq","Iraq","🇮🇶","I",58,0,2,"The Lions of Mesopotamia return after 40 years away."],
  ["nor","Norway","🇳🇴","I",32,0,4,"First cup since '98 — built around the most feared striker on earth."],
  ["arg","Argentina","🇦🇷","J",1,3,19,"Defending champions — streetwise, ferocious, and still hungry."],
  ["alg","Algeria","🇩🇿","J",36,0,5,"Desert Foxes with wing wizardry and a wounded-pride mission."],
  ["aut","Austria","🇦🇹","J",23,0,8,"The most aggressive pressing scheme at the tournament."],
  ["jor","Jordan","🇯🇴","J",68,0,1,"Asian Cup finalists making a historic first appearance."],
  ["por","Portugal","🇵🇹","K",6,0,9,"Nations League winners loaded with attacking riches across eras."],
  ["cod","DR Congo","🇨🇩","K",60,0,2,"The Leopards — athletic, fearless, and back after 52 years."],
  ["uzb","Uzbekistan","🇺🇿","K",62,0,1,"Debutants with the best youth pipeline in Asian football."],
  ["col","Colombia","🇨🇴","K",13,0,7,"Copa finalists — rhythm, flair, and a No.10 conducting everything."],
  ["eng","England","🏴󠁧󠁢󠁥󠁮󠁧󠁿","L",4,1,17,"Perennial contenders — a generational attack chasing the one that matters."],
  ["cro","Croatia","🇭🇷","L",10,0,7,"Finalists in '18, third in '22 — midfield royalty one last dance."],
  ["gha","Ghana","🇬🇭","L",54,0,5,"The Black Stars: direct, dynamic, and dangerous to anyone."],
  ["pan","Panama","🇵🇦","L",35,0,2,"CONCACAF's overachievers — compact and counter-punching."],
].map(a=>({id:a[0],name:a[1],flag:a[2],group:a[3],rank:a[4],titles:a[5],apps:a[6],summary:a[7]}));

export const TEAM = Object.fromEntries(T.map(t=>[t.id,t]));
export const GROUPS = "ABCDEFGHIJKL".split("").map(g=>({g,teams:T.filter(t=>t.group===g)}));

export const DETAILS = {
  par:{intro:"Gustavo Alfaro has transformed Paraguay into one of the hardest teams in the world to play against.",
    style:"Defensive organisation with a set-piece focus, physical midfield play, tactical discipline, and a habit of low-scoring matches.",
    strengths:"Defensive solidity, set pieces, organisation, and a strong mentality.",
    weaknesses:"Limited attacking creativity and a dependence on set pieces and narrow margins.",
    outlook:"Dark horse capable of frustrating stronger opponents and qualifying.",
    keyPlayers:["Gustavo Gómez","Antonio Sanabria","Julio Enciso","Andrés Cubas","Diego Gómez"],
    coach:"Gustavo Alfaro"},
  tur:{intro:"Türkiye return to the World Cup after a long absence with one of the tournament\'s most entertaining squads.",
    style:"Attacking football with a fluid front line, creative midfield, high-tempo transitions, and a front-foot mentality.",
    strengths:"Technical quality, creativity, exciting young stars, and attacking depth.",
    weaknesses:"Defensive vulnerability, centre-back depth, and consistency.",
    outlook:"Many view Türkiye as favourites to win the group.",
    keyPlayers:["Arda Güler","Kenan Yıldız","Hakan Çalhanoğlu","Orkun Kökçü","Ferdi Kadıoğlu"]},
  aus:{intro:"Tony Popovic has prioritised defensive structure and discipline since taking charge of Australia.",
    style:"A compact defensive block with a set-piece focus, physical football, organised shape, and a counter-attacking approach.",
    strengths:"Organisation, experience, defensive resilience, and set pieces.",
    weaknesses:"Limited attacking creativity and questions around goalscoring.",
    outlook:"Capable of competing for qualification through consistency and discipline.",
    keyPlayers:["Matthew Ryan","Harry Souttar","Martin Boyle","Christian Volpato","Nestor Irankunda"],
    coach:"Tony Popovic"},
  ecu:{intro:"Ecuador possess one of the best defensive units in international football.",
    style:"Defensive organisation with midfield intensity, a set-piece threat, and a habit of low-scoring matches.",
    strengths:"An elite defence, physicality, structure, and midfield quality.",
    weaknesses:"Goalscoring production and a reliance on narrow victories.",
    outlook:"Dangerous dark horse capable of a deep run.",
    keyPlayers:["Moisés Caicedo","Piero Hincapié","Willian Pacho","Joel Ordóñez","Enner Valencia"]},
  civ:{intro:"African champions return to the World Cup with a balanced and talented squad.",
    style:"Defensive strength with quick transitions, flexible formations, and athletic attacking play.",
    strengths:"Depth, athleticism, defensive organisation, and attacking options.",
    weaknesses:"The pressure of expectations and the need for consistent finishing.",
    outlook:"One of Africa\'s strongest hopes for a deep tournament run.",
    keyPlayers:["Amad Diallo","Nicolas Pépé","Yahia Fofana","Franck Kessié","Ousmane Diomande"]},
  cuw:{intro:"The smallest nation ever to reach the World Cup, Curaçao are one of the stories of the tournament.",
    style:"Dutch-influenced football — playing out from the back, a technical midfield approach, and positive attacking intent.",
    strengths:"Team spirit, technical players, and a strong project culture.",
    weaknesses:"Lack of World Cup experience, a difficult group, and a physical mismatch against stronger opponents.",
    outlook:"Underdogs, but already one of the success stories of the tournament.",
    keyPlayers:["Leandro Bacuna","Juninho Bacuna","Eloy Room","Jürgen Locadia","Tahith Chong"]},
  ned:{intro:"The Dutch possess quality throughout the squad but questions remain regarding goalscoring and tactical flexibility.",
    style:"A 4-3-3 system built on possession football, strong midfield control, and attacking full-backs.",
    strengths:"Midfield depth, defensive quality, and goalkeeping options.",
    weaknesses:"The centre-forward position, tactical rigidity, and consistency.",
    outlook:"Expected to qualify but face questions against elite opponents.",
    keyPlayers:["Virgil van Dijk","Ryan Gravenberch","Tijjani Reijnders","Donyell Malen","Xavi Simons"]},
  jpn:{intro:"One of the most well-drilled teams in the tournament under Hajime Moriyasu.",
    style:"Aggressive pressing within an organised structure, fast transitions, and tactical discipline.",
    strengths:"Pressing intensity, organisation, and team chemistry.",
    weaknesses:"Injuries to key attackers and a reliance on system over individual brilliance.",
    outlook:"Strong contender to win the group.",
    keyPlayers:["Takefusa Kubo","Daizen Maeda","Wataru Endo","Kaoru Mitoma","Ayase Ueda"],
    coach:"Hajime Moriyasu"},
  swe:{intro:"Sweden return after navigating the playoffs but arrive with defensive concerns.",
    style:"Direct attacking football with a reliance on forwards and a structured defensive setup.",
    strengths:"Elite attacking talent, physicality, and a counter-attacking threat.",
    weaknesses:"Defensive instability and a lack of creativity from deeper areas.",
    outlook:"Must outscore opponents to challenge for qualification.",
    keyPlayers:["Alexander Isak","Viktor Gyökeres","Benjamin Nygren","Gabriel Gudmundsson"]},
  tun:{intro:"Tunisia qualified without conceding a goal and remain committed to defensive football.",
    style:"A compact defensive block with counter-attacking football, a set-piece focus, and a low-risk approach.",
    strengths:"Organisation, defensive discipline, and tournament experience.",
    weaknesses:"Lack of goals and limited attacking ambition.",
    outlook:"Could frustrate stronger teams but need more attacking output to progress.",
    keyPlayers:["Ali Abdi","Ellyes Skhiri","Ismaël Gharbi","Dylan Bronn","Aïssa Laïdouni"]},
  bel:{intro:"Belgium enter the World Cup under Rudi Garcia with a talented squad blending experienced stars and an emerging generation.",
    style:"Attacking football in a four-at-the-back system with a creative midfield structure, aggressive attacking transitions, and an emphasis on scoring over defensive caution.",
    strengths:"Attacking talent, midfield quality, goalkeeping depth, and exciting young defenders.",
    weaknesses:"Defensive vulnerability, a lack of resilience in high-pressure knockout matches, and a tendency to concede goals.",
    outlook:"Strong favourites to win the group and potential neutrals\' favourite due to their attacking style.",
    keyPlayers:["Kevin De Bruyne","Romelu Lukaku","Jérémy Doku","Leandro Trossard","Amadou Onana","Thibaut Courtois"],
    coach:"Rudi Garcia"},
  egy:{intro:"Egypt arrive hoping to secure their first ever World Cup victory, with Mohamed Salah leading the charge.",
    style:"A defensive structure with quick transitions, direct attacks through wide forwards, and counter-attacking football built around star attackers.",
    strengths:"Counter-attacking threat, experience, elite attacking stars, and tournament motivation.",
    weaknesses:"Limited squad depth, dependence on Salah and Marmoush, and a lack of dominance in possession.",
    outlook:"Expected to battle Iran for second place and potentially make history with a first World Cup win.",
    keyPlayers:["Mohamed Salah","Omar Marmoush","Trezeguet","Zizo","Emam Ashour","Mohamed El Shenawy"]},
  irn:{intro:"Iran enter the tournament after an impressive qualification campaign and with significant motivation.",
    style:"Tactical flexibility built on counter-attacking football, physical presence, a set-piece threat, and defensive organisation.",
    strengths:"Tournament experience, tactical adaptability, dangerous counter attacks, and a strong mentality.",
    weaknesses:"An ageing squad, a disrupted domestic season, off-field distractions, and fitness concerns.",
    outlook:"Capable of reaching the knockout rounds if they start strongly.",
    keyPlayers:["Mehdi Taremi","Sardar Azmoun","Mehdi Ghayedi","Alireza Beiranvand"]},
  nzl:{intro:"The lowest-ranked team in the tournament arrives with little pressure but significant ambition.",
    style:"A deep defensive block with an organised structure, set-piece focus, direct football, and reliance on target-man play.",
    strengths:"Team chemistry, defensive organisation, leadership, and an aerial threat.",
    weaknesses:"Squad depth, defensive quality against elite opposition, and a lack of tournament-level experience.",
    outlook:"Underdogs, but capable of competing for points in a relatively open group.",
    keyPlayers:["Chris Wood","Elijah Just","Joe Bell","Michael Boxall","Liberato Cacace"]},
  uru:{intro:"Uruguay possess significant talent but arrive with questions surrounding form, goalscoring, and the longevity of Marcelo Bielsa\'s project.",
    style:"High-intensity pressing with direct attacking football, aggressive transitions, and physical midfield play.",
    strengths:"Midfield quality, tournament pedigree, tactical intensity, and defensive experience.",
    weaknesses:"Goalscoring inconsistency, squad harmony concerns, and injury issues.",
    outlook:"Expected to qualify but face uncertainty beyond the group stage.",
    keyPlayers:["Federico Valverde","Darwin Núñez","Ronald Araújo","Giorgian De Arrascaeta","Maxi Araújo"],
    coach:"Marcelo Bielsa"},
  ksa:{intro:"Saudi Arabia enter the tournament after managerial upheaval and concerns about squad development.",
    style:"Defensive organisation with structured midfield play, counter-attacking football, and a reliance on experienced players.",
    strengths:"Team familiarity, defensive discipline, and experience.",
    weaknesses:"Lack of goals, limited attacking options, and managerial uncertainty.",
    outlook:"Could struggle to escape the group and may finish bottom.",
    keyPlayers:["Mohammed Kanno","Salem Al-Dawsari","Mohammed Al-Owais"]},
  cpv:{intro:"One of the stories of the tournament, Cape Verde arrive with no pressure and enormous enthusiasm.",
    style:"An organised defensive structure with physical football, freedom for attacking players, and a direct attacking approach.",
    strengths:"Team spirit, defensive organisation, strong chemistry, and a fearless mentality.",
    weaknesses:"Lack of World Cup experience, squad depth, and overall quality compared to favourites.",
    outlook:"Potential surprise package capable of upsetting more established nations.",
    keyPlayers:["Ryan Mendes","Logan Costa","Livramento","Giovanni Cabral","Dailon Rocha Livramento"]},
  sen:{intro:"The African champions arrive believing they can make a deep run in the tournament.",
    style:"Physical midfield dominance with fast transitions, an organised defensive structure, and direct attacking football.",
    strengths:"Athleticism, midfield quality, squad unity, and tournament belief.",
    weaknesses:"Finishing consistency against elite opposition.",
    outlook:"Strong candidate to reach the knockout rounds and potentially go much further.",
    keyPlayers:["Sadio Mané","Nicolas Jackson","Ismaïla Sarr","Pape Matar Sarr","Édouard Mendy"]},
  nor:{intro:"Norway return to the World Cup with one of the most exciting attacking groups in the tournament.",
    style:"A flexible attacking system with direct football, creative playmaking, and aggressive wing play.",
    strengths:"Elite attacking talent, tactical flexibility, and goalscoring ability.",
    weaknesses:"Defensive vulnerability, a lack of tournament experience, and goalkeeper questions.",
    outlook:"Expected to challenge Senegal for qualification and could become a dangerous knockout opponent.",
    keyPlayers:["Erling Haaland","Martin Ødegaard","Alexander Sørloth","Antonio Nusa","Julian Ryerson"]},
  irq:{intro:"Iraq arrive after a difficult but inspirational qualification journey and enter arguably the toughest group in the tournament.",
    style:"A hard-working defensive structure with physical football, a counter-attacking approach, and strong team spirit.",
    strengths:"Resilience, organisation, adaptability, and a strong mentality.",
    weaknesses:"The quality gap compared to group rivals, a lack of elite-level depth, and difficult fixtures.",
    outlook:"Capable of causing an upset but face an enormous challenge to qualify.",
    keyPlayers:["Ali Al-Hamadi","Amir Al-Ammari","Marco Farji"]},
  aut:{intro:"Returning to the World Cup for the first time since 1998 under Ralf Rangnick.",
    style:"High pressing with aggressive transitions and front-foot football.",
    strengths:"A clear tactical identity, energy, and midfield intensity.",
    weaknesses:"Goalscoring depth and injuries.",
    outlook:"Strong candidate to qualify from the group.",
    keyPlayers:["Marko Arnautović","Konrad Laimer","Xaver Schlager","Nicolas Seiwald"],
    coach:"Ralf Rangnick"},
  alg:{intro:"One of Africa\'s most technically gifted sides.",
    style:"Possession football mixed with quick attacking combinations.",
    strengths:"Technical quality and attacking talent.",
    weaknesses:"Goalkeeping uncertainty and defensive consistency.",
    outlook:"Could challenge Austria for second place.",
    keyPlayers:["Riyad Mahrez","Amine Gouiri","Mohamed Amoura","Ibrahim Maza"]},
  jor:{intro:"World Cup debutants entering with confidence.",
    style:"Compact defending with quick counter-attacks in a 3-4-3 system.",
    strengths:"Team spirit and tactical discipline.",
    weaknesses:"Lack of experience and squad depth.",
    outlook:"Underdogs but capable of causing an upset.",
    keyPlayers:["Mousa Al-Tamari","Ali Olwan"]},
  por:{intro:"One of the deepest and most talented squads in the tournament.",
    style:"Possession football with technical midfield control and attacking flexibility.",
    strengths:"Depth, midfield quality, and experience.",
    weaknesses:"Wide attacking consistency and dependence on Ronaldo\'s role.",
    outlook:"Expected to top the group and make a deep tournament run.",
    keyPlayers:["Cristiano Ronaldo","Bruno Fernandes","Vitinha","João Neves","Nuno Mendes"]},
  col:{intro:"Back at the World Cup after missing 2022.",
    style:"Dynamic attacking football with strong wing play.",
    strengths:"Creativity, balance, and tournament energy.",
    weaknesses:"Finishing consistency.",
    outlook:"Strong favourite for second place and a possible quarter-finalist.",
    keyPlayers:["Luis Díaz","James Rodríguez","Jefferson Lerma","Richard Ríos"]},
  cod:{intro:"First World Cup appearance since 1974.",
    style:"Defensive organisation and counter-attacking football.",
    strengths:"Physicality and defensive resilience.",
    weaknesses:"Limited attacking firepower.",
    outlook:"Dangerous underdog capable of frustrating stronger sides.",
    keyPlayers:["Chancel Mbemba","Aaron Wan-Bissaka","Axel Tuanzebe","Cédric Bakambu"]},
  uzb:{intro:"Making their World Cup debut after years of near misses.",
    style:"Structured possession football with growing tactical flexibility.",
    strengths:"Organisation and emerging talent.",
    weaknesses:"Lack of experience at this level.",
    outlook:"Fighting DR Congo for third place and outside qualification hopes.",
    keyPlayers:["Abdukodir Khusanov","Eldor Shomurodov"]},
  cro:{intro:"Transitioning from their golden generation but still highly competitive.",
    style:"Technical football with midfield control and tactical intelligence.",
    strengths:"Experience, composure, and tournament pedigree.",
    weaknesses:"An ageing core and limited attacking explosiveness.",
    outlook:"Favourites to qualify alongside England.",
    keyPlayers:["Luka Modrić","Mateo Kovačić","Joško Gvardiol","Ivan Perišić"]},
  gha:{intro:"Talented but difficult to assess after managerial changes.",
    style:"Athletic football with direct attacks and transitions.",
    strengths:"Individual quality and physicality.",
    weaknesses:"Tactical cohesion.",
    outlook:"Main challenger to Croatia for second place.",
    keyPlayers:["Mohammed Kudus","Thomas Partey","Iñaki Williams"]},
  pan:{intro:"Hard-working side looking to compete in every match.",
    style:"A compact defensive structure and quick counters.",
    strengths:"Organisation and work rate.",
    weaknesses:"The quality gap against stronger opponents.",
    outlook:"Underdogs likely targeting third place.",
    keyPlayers:["Adalberto Carrasquilla","José Fajardo"]},

  rsa:{intro:"South Africa return to the World Cup for the first time since 2010. The squad is built around chemistry and continuity, with many players developed and still playing domestically.",
    style:"A disciplined 4-2-3-1 structure with a team-first approach, relying on chemistry and work rate.",
    strengths:"Strong team spirit, continuity under Hugo Broos, local chemistry, and growing belief following AFCON performances.",
    weaknesses:"Poor recent results, limited international experience, administrative issues, and a lack of elite-level depth.",
    outlook:"Underdogs capable of surprising teams through organisation and collective belief.",
    keyPlayers:["Teboho Mokoena","Ronwen Williams","Siyabonga Ngezana","Relebohile Mofokeng","Lyle Foster"],
    coach:"Hugo Broos"},
  kor:{intro:"South Korea possess one of the most talented squads in the group but enter with concerns surrounding form and tactical changes.",
    style:"A shift from a back four to a 3-4-3, with technical quality across the squad, attacking intent, and a flexible midfield structure.",
    strengths:"Elite individual talent, experience, technical quality, and an established core.",
    weaknesses:"Recent heavy defeats, defensive instability, uncertainty surrounding the new system, and key players arriving out of form.",
    outlook:"Capable of winning the group but difficult to predict due to recent performances.",
    keyPlayers:["Son Heung-min","Kim Min-jae","Lee Kang-in","Hwang In-beom","Lee Jae-sung","Jens Castrop"]},
  cze:{intro:"Returning to the World Cup for the first time since 2006, Czechia arrive with confidence after navigating a dramatic qualification journey.",
    style:"Physical and organised with direct attacking football, a strong set-piece threat, and tactical discipline.",
    strengths:"Momentum, set pieces, an experienced spine, and a reliable goalscorer in Schick.",
    weaknesses:"Reliance on Schick for goals, limited creativity outside key players, and less depth than some rivals.",
    outlook:"One of the dark horses in the group and a genuine contender for qualification.",
    keyPlayers:["Patrik Schick","Pavel Šulc","Tomáš Souček","Tomáš Holeš","Vladimír Coufal"]},
  sui:{intro:"Switzerland remain one of the most dependable tournament teams in international football. They consistently reach knockout rounds and rarely underperform.",
    style:"An organised defensive structure with efficient possession, strong midfield partnerships, and tactical discipline.",
    strengths:"Experience, squad continuity, strong defensive partnerships, and the ability to consistently beat lower-ranked opponents.",
    weaknesses:"An ageing core in certain areas and the lack of a prolific elite striker.",
    outlook:"Strong favourites to top the group.",
    keyPlayers:["Manuel Akanji","Nico Elvedi","Granit Xhaka","Remo Freuler","Ardon Jashari","Noah Okafor","Breel Embolo"]},
  can:{intro:"Canada arrive as arguably the most settled of the host nations. Jesse Marsch has implemented an energetic, high-intensity style that suits the athletic profile of the squad.",
    style:"High pressing and vertical attacking football — Red Bull-inspired intensity with fast transitions.",
    strengths:"Athleticism, home support, a clear tactical identity, and attacking pace.",
    weaknesses:"Defensive consistency, goalkeeper questions, and several key players not arriving in peak form.",
    outlook:"Strong contender for second place and knockout qualification.",
    keyPlayers:["Alphonso Davies","Jonathan David","Promise David","Ismaël Koné","Stephen Eustáquio","Tajon Buchanan","Liam Millar"],
    coach:"Jesse Marsch"},
  bih:{intro:"Bosnia & Herzegovina are one of the surprise qualifiers after overcoming Wales and Italy in the playoffs.",
    style:"A compact defensive structure with direct football, an experience-led approach, and a threat from wide areas.",
    strengths:"Leadership, defensive resilience, and exciting young talent emerging alongside experienced veterans.",
    weaknesses:"An inexperienced midfield and a lack of depth compared to rivals.",
    outlook:"Capable of challenging for qualification and difficult to break down.",
    keyPlayers:["Edin Džeko","Sead Kolašinac","Amar Dedić","Muharemović","Bajraktarević","Ali Begović"]},
  qat:{intro:"Qatar return to the World Cup after hosting the previous edition. The squad is highly familiar with one another due to the domestic-based nature of the group.",
    style:"Structured defensive football with patient build-up, relying on chemistry and familiarity.",
    strengths:"Experience together, strong understanding between players, and familiarity with tournament football.",
    weaknesses:"An ageing squad, limited depth, and a lack of players competing in top European leagues.",
    outlook:"Likely outsiders but capable of making games difficult through organisation.",
    keyPlayers:["Akram Afif","Almoez Ali","Hassan Al-Haydos"]},
  mar:{intro:"Morocco arrive with a deeper squad than the team that reached the 2022 semi-finals and are viewed as one of the strongest dark horses in the tournament.",
    style:"Organised defending with dangerous transitions, strong wide play, and a technically gifted midfield.",
    strengths:"Depth, balance between youth and experience, and quality across multiple positions.",
    weaknesses:"Pressure created by increased expectations and a relatively new coaching setup.",
    outlook:"Capable of another deep knockout run.",
    keyPlayers:["Achraf Hakimi","Bilal El Khannouss","Ismael Saibari","Ayyoub Bouaddi","Abde Ezzalzouli","Brahim Díaz","Ayoub El Kaabi"]},
  hai:{intro:"Haiti return to the World Cup for the first time since 1974 and arrive after successfully recruiting a number of dual-nationality players.",
    style:"Direct football with vertical attacks and a counter-attacking approach.",
    strengths:"Athleticism, motivation, an improving talent pool, and a direct style.",
    weaknesses:"Limited World Cup experience, squad cohesion, and depth compared to rivals.",
    outlook:"Outsiders, but capable of troubling stronger teams.",
    keyPlayers:["Wilson Isidor","Jean-Ricner Bellegarde","Danley Jean Jacques","Frantzdy Pierrot","Duckens Nazon"]},
  sco:{intro:"Scotland arrive with momentum after an emotional qualification campaign and rely heavily on continuity and team chemistry.",
    style:"A structured, midfield-driven approach with wing-backs providing width and a strong collective identity.",
    strengths:"Chemistry, leadership, midfield quality, and experience playing together.",
    weaknesses:"Lack of elite goalscorers, defensive depth, and injuries in key areas.",
    outlook:"Strong candidate to challenge for qualification, particularly through a best third-place route.",
    keyPlayers:["Scott McTominay","John McGinn","Ryan Christie","Andy Robertson","Aaron Hickey","Ross Stewart"]},

  bra:{intro:"Brazil arrive with enormous talent and Carlo Ancelotti in charge. They remain one of the most feared teams in the competition.",
    keyPlayers:["Vinícius Júnior","Raphinha","Neymar","Casemiro","Bremer","Gabriel","Endrick"],
    style:"Attacking football with positional freedom, a fluid front line, and an emphasis on creativity.",
    strengths:"Elite attacking depth, experience, a world-class manager, and game-changing individuals.",
    weaknesses:"Full-back depth, midfield balance, and defensive transitions.",
    outlook:"Potential title challengers capable of reaching the latter stages.",
    ptw:{n:"Vinícius Jr.",c:"Real Madrid",why:"Unplayable on his day — the tournament's biggest one-v-one mismatch."},
    bo:{n:"Estêvão",c:"Chelsea",why:"Teenage winger with the audacity to own the biggest stage."},
    coach:"Carlo Ancelotti",assts:["Davide Ancelotti","Paul Clement"],
    squad:[["GK","A. Becker","Liverpool",0],["GK","Bento","Al-Nassr",0],["DF","Marquinhos","PSG",1],["DF","G. Magalhães","Arsenal",0],["DF","É. Militão","Real Madrid",0],["DF","Danilo","Flamengo",0],["DF","Wendell","São Paulo",0],["MF","B. Guimarães","Newcastle",0],["MF","Casemiro","Man United",0],["MF","L. Paquetá","West Ham",0],["MF","Andreas Pereira","Fulham",0],["FW","Vinícius Jr.","Real Madrid",0],["FW","Rodrygo","Real Madrid",0],["FW","Raphinha","Barcelona",0],["FW","Estêvão","Chelsea",0],["FW","G. Jesus","Arsenal",0]]},
  arg:{intro:"Defending champions with a settled squad under Lionel Scaloni.",
    keyPlayers:["Lionel Messi","Julián Álvarez","Lautaro Martínez","Enzo Fernández","Alexis Mac Allister"],
    style:"Possession-based football with midfield control and fluid attacking transitions.",
    strengths:"Tournament experience, squad chemistry, and a winning mentality.",
    weaknesses:"Reliance on ageing stars and midfield form.",
    outlook:"Strong favourites to win the group and contenders to reach the semi-finals or beyond.",
    ptw:{n:"Lionel Messi",c:"Inter Miami",why:"One last dance. Every touch will stop the stadium."},
    bo:{n:"Franco Mastantuono",c:"Real Madrid",why:"18-year-old playmaker already trusted in the biggest moments."},
    coach:"Lionel Scaloni",assts:["Pablo Aimar","Walter Samuel"],
    squad:[["GK","E. Martínez","Aston Villa",0],["DF","C. Romero","Tottenham",0],["DF","L. Martínez","Inter",0],["DF","N. Molina","Atlético Madrid",0],["DF","N. Tagliafico","Lyon",0],["MF","E. Fernández","Chelsea",0],["MF","A. Mac Allister","Liverpool",0],["MF","R. De Paul","Inter Miami",0],["MF","F. Mastantuono","Real Madrid",0],["FW","L. Messi","Inter Miami",1],["FW","J. Álvarez","Atlético Madrid",0],["FW","L. Martínez","Inter",0],["FW","N. González","Juventus",0]]},
  fra:{intro:"France enter the World Cup with arguably the deepest squad in international football and one final tournament under Didier Deschamps.",
    keyPlayers:["Kylian Mbappé","Michael Olise","Ousmane Dembélé","William Saliba","Eduardo Camavinga"],
    style:"Flexible attacking football with elite transition play, tactical adaptability, and a strong defensive structure.",
    strengths:"World-class talent, depth across every position, tournament experience, and match winners throughout the squad.",
    weaknesses:"Potential dressing-room distractions, managing star personalities, and occasional inconsistency.",
    outlook:"One of the leading favourites to win the World Cup.",
    ptw:{n:"Kylian Mbappé",c:"Real Madrid",why:"The face of the tournament — chasing the Golden Boot and redemption."},
    bo:{n:"Désiré Doué",c:"PSG",why:"Champions-League-final hero ready to detonate on the world stage."},
    coach:"Didier Deschamps",assts:["Guy Stéphan","Franck Raviot"],
    squad:[["GK","M. Maignan","AC Milan",0],["DF","W. Saliba","Arsenal",0],["DF","I. Konaté","Liverpool",0],["DF","T. Hernández","Al-Hilal",0],["DF","J. Koundé","Barcelona",0],["MF","A. Tchouaméni","Real Madrid",0],["MF","E. Camavinga","Real Madrid",0],["MF","M. Zaïre-Emery","PSG",0],["FW","K. Mbappé","Real Madrid",1],["FW","O. Dembélé","PSG",0],["FW","D. Doué","PSG",0],["FW","M. Olise","Bayern Munich",0]]},
  eng:{intro:"Thomas Tuchel\'s first World Cup in charge of England.",
    keyPlayers:["Harry Kane","Jude Bellingham","Declan Rice","Bukayo Saka","Jordan Pickford"],
    style:"Structured possession with strong midfield control and reliance on Harry Kane\'s finishing.",
    strengths:"A strong starting XI, tournament experience, and squad balance.",
    weaknesses:"Pressure, mentality in knockout matches, and goals beyond Kane.",
    outlook:"Expected to win the group and challenge for the title.",
    ptw:{n:"Jude Bellingham",c:"Real Madrid",why:"Box-to-box royalty who lives for the decisive moment."},
    bo:{n:"Myles Lewis-Skelly",c:"Arsenal",why:"Fearless teenager who's made the impossible look routine."},
    coach:"Thomas Tuchel",assts:["Anthony Barry"],
    squad:[["GK","J. Pickford","Everton",0],["DF","J. Stones","Man City",0],["DF","M. Guéhi","Liverpool",0],["DF","T. Alexander-Arnold","Real Madrid",0],["DF","M. Lewis-Skelly","Arsenal",0],["MF","D. Rice","Arsenal",0],["MF","J. Bellingham","Real Madrid",0],["MF","C. Palmer","Chelsea",0],["FW","H. Kane","Bayern Munich",1],["FW","B. Saka","Arsenal",0],["FW","P. Foden","Man City",0],["FW","A. Gordon","Newcastle",0]]},
  ger:{intro:"Germany arrive with plenty of talent but also uncertainty. Julian Nagelsmann is balancing a transition between experienced veterans and a younger generation.",
    keyPlayers:["Jamal Musiala","Florian Wirtz","Joshua Kimmich","Manuel Neuer","Jonathan Tah"],
    style:"Possession football with a flexible attacking structure, technical midfield control, and high pressing.",
    strengths:"Midfield quality, attacking creativity, and tournament experience.",
    weaknesses:"Goalkeeper decisions, lack of a proven striker, and tactical uncertainty.",
    outlook:"Strong contender to progress but not among the very top favourites.",
    ptw:{n:"Jamal Musiala",c:"Bayern Munich",why:"The slalom dribbler defenses simply cannot plan for."},
    bo:{n:"Florian Wirtz",c:"Liverpool",why:"Already world-class — this is the tournament the world finds out."},
    coach:"Julian Nagelsmann",assts:["Sandro Wagner","Benjamin Glück"],
    squad:[["GK","M. ter Stegen","Barcelona",0],["DF","A. Rüdiger","Real Madrid",0],["DF","J. Tah","Bayern Munich",0],["DF","J. Kimmich","Bayern Munich",1],["DF","D. Raum","RB Leipzig",0],["MF","Pavlović","Bayern Munich",0],["MF","F. Wirtz","Liverpool",0],["MF","J. Musiala","Bayern Munich",0],["FW","K. Havertz","Arsenal",0],["FW","L. Sané","Galatasaray",0],["FW","N. Woltemade","Newcastle",0]]},
  esp:{intro:"Spain arrive as one of the leading favourites after winning the European Championship and assembling one of the deepest squads in world football.",
    keyPlayers:["Lamine Yamal","Rodri","Pedri","Nico Williams","Álvaro Morata","Fabián Ruiz"],
    style:"Possession football with high pressing, technical midfield control, flexible attacking rotations, and dominant ball retention.",
    strengths:"Squad depth, midfield quality, tactical flexibility, and a winning mentality.",
    weaknesses:"Occasional vulnerability to transitions and the expectations of being favourites.",
    outlook:"Expected to win the group and challenge strongly for the World Cup title.",
    ptw:{n:"Lamine Yamal",c:"Barcelona",why:"18 and already the most-watched footballer alive."},
    bo:{n:"Pau Cubarsí",c:"Barcelona",why:"Teen center-back who defends like he's seen everything twice."},
    coach:"Luis de la Fuente",assts:["Pablo Amo"],
    squad:[["GK","U. Simón","Athletic Club",0],["DF","P. Cubarsí","Barcelona",0],["DF","R. Le Normand","Atlético Madrid",0],["DF","M. Cucurella","Chelsea",0],["DF","D. Carvajal","Real Madrid",0],["MF","Rodri","Man City",1],["MF","Pedri","Barcelona",0],["MF","F. Ruiz","PSG",0],["FW","L. Yamal","Barcelona",0],["FW","N. Williams","Athletic Club",0],["FW","M. Oyarzabal","Real Sociedad",0]]},
  usa:{intro:"The USA enter the World Cup under Mauricio Pochettino with high expectations but significant questions. The squad possesses attacking quality and depth, though concerns remain in defence and goal.",
    keyPlayers:["Christian Pulisic","Folarin Balogun","Ricardo Pepi","Sergiño Dest","Antonee Robinson","Tyler Adams"],
    style:"A back-three system with aggressive wing-backs, direct attacking transitions, creative attacking midfielders, and a flexible attacking structure.",
    strengths:"Home advantage, attacking talent, tactical flexibility, and depth in forward areas.",
    weaknesses:"Goalkeeping uncertainty, defensive consistency, and midfield depth.",
    outlook:"Expected to challenge for first place and reach the knockout rounds.",
    ptw:{n:"Christian Pulisic",c:"AC Milan",why:"Captain America, in form, in front of home crowds."},
    bo:{n:"Diego Luna",c:"Real Salt Lake",why:"Fearless creator who plays every game like a street final."},
    coach:"Mauricio Pochettino",assts:["Jesús Pérez","Miguel D'Agostino"],
    squad:[["GK","M. Turner","Lyon",0],["DF","C. Richards","Crystal Palace",0],["DF","A. Robinson","Fulham",0],["DF","S. Dest","PSV",0],["MF","T. Adams","Bournemouth",1],["MF","W. McKennie","Juventus",0],["MF","Y. Musah","Atalanta",0],["FW","C. Pulisic","AC Milan",0],["FW","T. Weah","Marseille",0],["FW","F. Balogun","Monaco",0],["FW","D. Luna","Real Salt Lake",0]]},
  mex:{intro:"Mexico enter the World Cup looking to erase the disappointment of their 2022 group-stage exit. Under Javier Aguirre, they have become more organised, pragmatic, and tactically flexible.",
    keyPlayers:["Edson Álvarez","Santiago Giménez","Raúl Jiménez","Johan Vásquez","César Montes","Gilberto Mora","Álvaro Fidalgo"],
    style:"Direct transitions with wingers moving into central areas and full-backs providing width — a structured defensive shape, less possession-focused than previous Mexico teams.",
    strengths:"Home advantage, strong recent form, tactical clarity, an experienced defensive core, and growing confidence.",
    weaknesses:"Goalkeeper uncertainty, lack of elite attacking creativity, pressure from supporters, and dependence on key attackers finding form.",
    outlook:"Mexico have a strong chance of topping the group and returning to the knockout rounds.",
    ptw:{n:"Santiago Giménez",c:"AC Milan",why:"The No.9 Mexico has waited a generation for."},
    bo:{n:"Gilberto Mora",c:"Tijuana",why:"17-year-old playmaker with the Azteca ready to crown him."},
    coach:"Javier Aguirre",assts:["Rafael Márquez"],
    squad:[["GK","L. Malagón","América",0],["DF","C. Montes","Lokomotiv",0],["DF","J. Vásquez","Genoa",0],["DF","J. Gallardo","Toluca",0],["MF","E. Álvarez","West Ham",1],["MF","L. Chávez","Dynamo Moscow",0],["MF","G. Mora","Tijuana",0],["FW","S. Giménez","AC Milan",0],["FW","H. Lozano","San Diego FC",0],["FW","A. Vega","Toluca",0]]},
};

// Group overviews — written by the site editor. Add more groups as content arrives.
export const GROUP_OVERVIEWS = {
  D: "Group D is one of the most balanced groups in the tournament. The United States bring home support and attacking talent, Türkiye arrive with exciting attacking football and growing confidence, Paraguay possess one of the most effective defensive systems in world football, and Australia offer discipline, organisation, and resilience.",
  E: "Group E features a fascinating mix of traditional power, defensive specialists, African contenders, and one of the greatest underdog stories of the tournament.",
  F: "Group F combines a European heavyweight, an emerging Asian power, an unpredictable Sweden side, and a defensive-minded Tunisia team.",
  G: "Group G may not have the star power of some other groups, but it offers fascinating storylines. Belgium begin a new era after the golden generation, Egypt hope Mohamed Salah can inspire history, Iran arrive carrying extra motivation amid off-field challenges, and New Zealand look to defy expectations as the tournament\'s lowest-ranked side.",
  H: "Group H contains one of the tournament favourites in Spain, a traditional South American power in Uruguay, a struggling Saudi Arabian side, and World Cup debutants Cape Verde.",
  I: "Group I is widely considered one of the toughest groups in the tournament. France are among the favourites to lift the trophy, Senegal are African champions, Norway possess one of the world\'s most dangerous attacks, and Iraq face a daunting challenge.",
  J: "Argentina headline Group J as defending world champions. Austria return to the World Cup after a long absence, Algeria bring one of Africa\'s most talented squads, and Jordan make their World Cup debut.",
  K: "Portugal enter as favourites in a group that also includes Colombia, DR Congo and World Cup debutants Uzbekistan.",
  L: "England lead Group L, joined by Croatia, Ghana and Panama. It combines a major contender, a proven tournament nation, and two sides hoping to surprise.",

  A: "Group A is one of the most open groups in the tournament. Mexico arrive with home advantage and renewed confidence under Javier Aguirre, South Korea possess the strongest collection of individual talent, Czechia enter the competition with momentum after a dramatic qualification campaign, and South Africa bring continuity, chemistry, and belief. No team enters as a clear favourite, making every match potentially decisive.",
  B: "Group B combines tournament experience, home support, underdog resilience, and an ambitious Qatar side. Switzerland enter as favourites, Canada appear the most settled host nation, Bosnia & Herzegovina arrive with momentum after dramatic qualification, and Qatar rely on familiarity and experience.",
  C: "Group C contains one of the tournament favourites, one of the strongest dark horses, an inspiring underdog story, and a Scotland side seeking to build on a memorable qualification campaign.",
};


// All known player names for a team — full squad if available, else key players.
export function playersOf(id) {
  const d = DETAILS[id] || {};
  const squad = (d.squad || []).map(row => Array.isArray(row) ? row[1] : row).filter(Boolean);
  if (squad.length) return squad;
  return (d.keyPlayers || []);
}
